### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by nekokatt** [bcroq/docker-stackless#2]
Morning!

Wondering if you are able to put up an image for Stackless Python 3.8? I understand it is still in preview 3.8.0b3, but it would be incredibly useful to our project if there was an image available on docker for this :)

**Comment by bcroq** [comment]
Do you have a link where I could get Stackless Python 3.8?

**Comment by bcroq** [comment]
Wikipedia says 3.8.0b3 is the latest preview release of stackless... this is an error because the v3.8.0b3 git tag is a Python tag, not a Stackless Python tag.

Stackless Python tags end with -slp, eg. v3.7.5-slp.
